// Vercel build step (vercel.json "buildCommand"): writes config.js from the
// project's PUBLIC_API_BASE_URL environment variable - the backend's public
// origin, e.g. https://<service>.onrender.com. No npm install, no bundler:
// the site stays the plain files in this repository.
//
// Fails the build rather than deploy a site that can't reach its backend,
// or that would send users' sign-ins over plain http.
import { writeFileSync } from 'node:fs';

function fail(message) {
  console.error(`write-config: ${message}`);
  process.exit(1);
}

const raw = (process.env.PUBLIC_API_BASE_URL || '').trim();
if (!raw) fail('PUBLIC_API_BASE_URL is not set - set it in the Vercel project (Settings > Environment Variables).');

let url;
try { url = new URL(raw); } catch { fail(`PUBLIC_API_BASE_URL is not a URL: ${raw}`); }
if (url.protocol !== 'https:') fail('PUBLIC_API_BASE_URL must be https:// - the site is served over https and browsers block http calls from it.');
if (url.username || url.password || url.search || url.hash) fail('PUBLIC_API_BASE_URL must be a plain origin (no credentials, query or fragment).');

const apiBaseUrl = url.href.replace(/\/+$/, '');
const config = `// Generated by scripts/write-config.mjs at build time - see the repository's config.js.
// Public values only.
window.SIRU_CONFIG = Object.freeze({
  apiBaseUrl: ${JSON.stringify(apiBaseUrl)},
});
`;
writeFileSync(new URL('../config.js', import.meta.url), config);
console.log(`write-config: config.js -> ${apiBaseUrl}`);
